version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/web-trace/static
    depends_on:
      - web
    restart: on-failure
  web:
    build: .
    platform: linux/amd64
    command: bash -c "python manage.py collectstatic &&
                      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/web-trace:rw
      - static_volume:/home/app/web-trace/static
    image:
      web-trace-app
    expose:
      - "8000"
    restart: on-failure

volumes:
  static_volume:
