version: "3.9"

services:
  waf:
    image: owasp/modsecurity-crs:3-apache
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./etc/apache2/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - static_volume:/home/app/web-trace/static
    environment:
      - PROXY=1
      - PARANOIA=1
      - BACKEND=http://web:8000
    restart: on-failure
  web:
    build: .
    platform: linux/amd64
    command: bash -c "python manage.py collectstatic --noinput &&
          gunicorn config.wsgi:application --bind 0.0.0.0:8000 --worker-tmp-dir  /dev/sh m--workers=2 --threads=4 --worker-class=gthread"
    volumes:
      - .:/web-trace:rw
      - static_volume:/home/app/web-trace/static
    image:
      web-trace-app
    expose:
      - "8000"
    restart: on-failure

volumes:
  static_volume:
