# Generated by Django 3.2.7 on 2021-09-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nric', models.CharField(max_length=9)),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default', models.CharField(max_length=20)),
                ('permissions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('active', models.BinaryField()),
                ('email', models.CharField(max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.role')),
            ],
        ),
        migrations.CreateModel(
            name='PositiveCases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_test_positive', models.DateField()),
                ('is_recovered', models.BinaryField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.identity')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vertex1_id', models.BigIntegerField()),
                ('vertex1_category', models.CharField(max_length=10)),
                ('vertex2_id', models.BigIntegerField()),
                ('vertex2_category', models.CharField(max_length=10)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='CloseContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.identity')),
                ('positivecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.positivecases')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.staff')),
            ],
        ),
    ]
