# Generated by Django 3.2.7 on 2021-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_auto_20210925_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='status',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='vertex1_category',
            field=models.CharField(choices=[('positive', 'positive case'), ('contact', 'close contact')], max_length=20),
        ),
        migrations.AlterField(
            model_name='edge',
            name='vertex2_category',
            field=models.CharField(choices=[('positive', 'positive case'), ('contact', 'close contact')], max_length=20),
        ),
        migrations.AlterField(
            model_name='positivecases',
            name='is_recovered',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='active',
            field=models.BinaryField(editable=True),
        ),
    ]
