# Generated by Django 3.2.7 on 2021-09-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("official", "0009_positivecases_cluster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positivecases",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official.cluster",
            ),
        ),
    ]
